[project]
authors = ["Alessandro Croci <alessandro.croci@iit.it>"]
channels = ["robostack-staging", "conda-forge"]
description = "Add a short description here"
name = "ros2_ws_pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"

[activation]
scripts = ["install/setup.sh"]
